export interface CountryBankConfig {
  countryCode: string;
  countryName: string;
  flag: string;
  currency: string;
  symbol: string;
  requiredFields: string[];
  fieldLabels: Record<string, string>;
  banks: Array<{ code: string; name: string }>;
}

export const COUNTRY_BANKS: Record<string, CountryBankConfig> = {
  US: {
    countryCode: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    currency: 'USD',
    symbol: '$',
    requiredFields: ['routing', 'accountNumber', 'recipientName'],
    fieldLabels: { routing: 'Routing Number (ABA)', accountNumber: 'Account Number', recipientName: 'Recipient Full Name' },
    banks: [
      { code: 'CHASE', name: 'JPMorgan Chase Bank' },
      { code: 'BOA', name: 'Bank of America' },
      { code: 'WELLS', name: 'Wells Fargo Bank' },
      { code: 'CITI', name: 'Citibank' },
      { code: 'CAPONE', name: 'Capital One Bank' },
      { code: 'PNC', name: 'PNC Bank' },
      { code: 'USATM', name: 'U.S. Bank' },
      { code: 'TRUIST', name: 'Truist Bank' },
      { code: 'GOLDMAN', name: 'Goldman Sachs' },
      { code: 'TD_US', name: 'TD Bank USA' },
    ],
  },
  GB: {
    countryCode: 'GB',
    countryName: 'United Kingdom',
    flag: '🇬🇧',
    currency: 'GBP',
    symbol: '£',
    requiredFields: ['sortCode', 'accountNumber', 'iban', 'recipientName'],
    fieldLabels: { sortCode: 'Sort Code (6 digits)', accountNumber: 'Account Number (8 digits)', iban: 'IBAN', recipientName: 'Account Name' },
    banks: [
      { code: 'BARCLAYS', name: 'Barclays Bank' },
      { code: 'HSBC_UK', name: 'HSBC UK' },
      { code: 'LLOYDS', name: 'Lloyds Bank' },
      { code: 'NATWEST', name: 'NatWest Bank' },
      { code: 'SANTANDER_UK', name: 'Santander UK' },
      { code: 'REVOLUT_UK', name: 'Revolut UK' },
      { code: 'MONZO', name: 'Monzo Bank' },
      { code: 'STARLING', name: 'Starling Bank' },
      { code: 'HALIFAX', name: 'Halifax' },
      { code: 'NATIONWIDE', name: 'Nationwide Building Society' },
    ],
  },
  NG: {
    countryCode: 'NG',
    countryName: 'Nigeria',
    flag: '🇳🇬',
    currency: 'NGN',
    symbol: '₦',
    requiredFields: ['bankName', 'accountNumber', 'recipientName'],
    fieldLabels: { bankName: 'Bank Name', accountNumber: 'NUBAN Account Number (10 digits)', recipientName: 'Account Name' },
    banks: [
      { code: 'ACCESS', name: 'Access Bank Nigeria' },
      { code: 'GTB', name: 'Guaranty Trust Bank (GTBank)' },
      { code: 'ZENITH', name: 'Zenith Bank' },
      { code: 'FIRSTBANK', name: 'First Bank of Nigeria' },
      { code: 'UBA', name: 'United Bank for Africa (UBA)' },
      { code: 'KUDA', name: 'Kuda Microfinance Bank' },
      { code: 'OPAY', name: 'OPay Digital Bank' },
      { code: 'PALMPAY', name: 'PalmPay Nigeria' },
      { code: 'STANBIC_NG', name: 'Stanbic IBTC Bank' },
      { code: 'FCMB', name: 'First City Monument Bank (FCMB)' },
      { code: 'STERLING', name: 'Sterling Bank' },
      { code: 'WEMA', name: 'Wema Bank / ALAT' },
    ],
  },
  AU: {
    countryCode: 'AU',
    countryName: 'Australia',
    flag: '🇦🇺',
    currency: 'AUD',
    symbol: 'A$',
    requiredFields: ['bsb', 'accountNumber', 'recipientName'],
    fieldLabels: { bsb: 'BSB Number (6 digits)', accountNumber: 'Account Number', recipientName: 'Account Name' },
    banks: [
      { code: 'CBA', name: 'Commonwealth Bank of Australia' },
      { code: 'ANZ', name: 'ANZ Bank' },
      { code: 'NAB', name: 'National Australia Bank (NAB)' },
      { code: 'WESTPAC', name: 'Westpac Banking Corporation' },
      { code: 'MACQUARIE', name: 'Macquarie Bank' },
      { code: 'ING_AU', name: 'ING Bank Australia' },
      { code: 'BENDIGO', name: 'Bendigo Bank' },
    ],
  },
  CA: {
    countryCode: 'CA',
    countryName: 'Canada',
    flag: '🇨🇦',
    currency: 'CAD',
    symbol: 'CA$',
    requiredFields: ['transit', 'institution', 'accountNumber', 'recipientName'],
    fieldLabels: { transit: 'Transit Number (5 digits)', institution: 'Institution Number (3 digits)', accountNumber: 'Account Number', recipientName: 'Account Name' },
    banks: [
      { code: 'RBC', name: 'Royal Bank of Canada (RBC)' },
      { code: 'TD_CA', name: 'TD Canada Trust' },
      { code: 'SCOTIA', name: 'Scotiabank' },
      { code: 'BMO', name: 'Bank of Montreal (BMO)' },
      { code: 'CIBC', name: 'CIBC Bank' },
      { code: 'DESJARDINS', name: 'Desjardins Group' },
    ],
  },
  DE: {
    countryCode: 'DE',
    countryName: 'Germany',
    flag: '🇩🇪',
    currency: 'EUR',
    symbol: '€',
    requiredFields: ['iban', 'swift', 'recipientName'],
    fieldLabels: { iban: 'IBAN (DE...)', swift: 'BIC / SWIFT Code', recipientName: 'Account Holder Name' },
    banks: [
      { code: 'DEUTSCHE', name: 'Deutsche Bank' },
      { code: 'COMMERZ', name: 'Commerzbank' },
      { code: 'N26', name: 'N26 Bank' },
      { code: 'SPARKASSE', name: 'Sparkasse' },
      { code: 'VOLKSBANK', name: 'Volksbanken Raiffeisenbanken' },
      { code: 'ING_DE', name: 'ING Germany' },
    ],
  },
  FR: {
    countryCode: 'FR',
    countryName: 'France',
    flag: '🇫🇷',
    currency: 'EUR',
    symbol: '€',
    requiredFields: ['iban', 'swift', 'recipientName'],
    fieldLabels: { iban: 'IBAN (FR...)', swift: 'BIC / SWIFT Code', recipientName: 'Account Holder Name' },
    banks: [
      { code: 'BNP', name: 'BNP Paribas' },
      { code: 'CREDIT_AG', name: 'Crédit Agricole' },
      { code: 'SOCIETE_GEN', name: 'Société Générale' },
      { code: 'BPCE', name: 'Groupe BPCE' },
      { code: 'BOURSORAMA', name: 'Boursorama Banque' },
    ],
  },
  IN: {
    countryCode: 'IN',
    countryName: 'India',
    flag: '🇮🇳',
    currency: 'INR',
    symbol: '₹',
    requiredFields: ['ifsc', 'accountNumber', 'recipientName'],
    fieldLabels: { ifsc: 'IFSC Code', accountNumber: 'Account Number', recipientName: 'Account Name' },
    banks: [
      { code: 'SBI', name: 'State Bank of India (SBI)' },
      { code: 'HDFC', name: 'HDFC Bank' },
      { code: 'ICICI', name: 'ICICI Bank' },
      { code: 'AXIS', name: 'Axis Bank' },
      { code: 'KOTAK', name: 'Kotak Mahindra Bank' },
      { code: 'PNB_IN', name: 'Punjab National Bank' },
    ],
  },
  ZA: {
    countryCode: 'ZA',
    countryName: 'South Africa',
    flag: '🇿🇦',
    currency: 'ZAR',
    symbol: 'R',
    requiredFields: ['branchCode', 'accountNumber', 'recipientName'],
    fieldLabels: { branchCode: 'Branch Code', accountNumber: 'Account Number', recipientName: 'Account Name' },
    banks: [
      { code: 'STANDARD_ZA', name: 'Standard Bank South Africa' },
      { code: 'FNB_ZA', name: 'First National Bank (FNB)' },
      { code: 'ABSA', name: 'Absa Bank' },
      { code: 'NEDBANK', name: 'Nedbank' },
      { code: 'CAPITEC', name: 'Capitec Bank' },
    ],
  },
  KE: {
    countryCode: 'KE',
    countryName: 'Kenya',
    flag: '🇰🇪',
    currency: 'KES',
    symbol: 'KSh',
    requiredFields: ['bankName', 'accountNumber', 'recipientName'],
    fieldLabels: { bankName: 'Bank / Paybill Name', accountNumber: 'Account / Mobile Number', recipientName: 'Recipient Name' },
    banks: [
      { code: 'EQUITY_KE', name: 'Equity Bank Kenya' },
      { code: 'KCB', name: 'KCB Bank Kenya' },
      { code: 'NCBA', name: 'NCBA Bank Kenya' },
      { code: 'MPESA', name: 'M-PESA Paybill / Till' },
      { code: 'COOP_KE', name: 'Co-operative Bank of Kenya' },
    ],
  },
  GH: {
    countryCode: 'GH',
    countryName: 'Ghana',
    flag: '🇬🇭',
    currency: 'GHS',
    symbol: 'GH₵',
    requiredFields: ['bankName', 'accountNumber', 'recipientName'],
    fieldLabels: { bankName: 'Bank / Mobile Money Provider', accountNumber: 'Account / Mobile Number', recipientName: 'Recipient Name' },
    banks: [
      { code: 'GCB', name: 'GCB Bank Limited' },
      { code: 'ECOBANK_GH', name: 'Ecobank Ghana' },
      { code: 'MTN_MOMO', name: 'MTN Mobile Money' },
      { code: 'VODAFONE_CASH', name: 'Vodafone Cash Ghana' },
      { code: 'FIDELITY_GH', name: 'Fidelity Bank Ghana' },
    ],
  },
};
